### ISSUE TITLE
Make it possible to filter for city as well as country

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/website#13]
It would be great if we could filter by city also, to see which companies helped in which cities.

**Comment by jepp2078** [comment]
I think this might be difficult to do right at this moment, as the meetup repository doesn't expose this.

I created an issue to add this:

https://github.com/cloud-native-nordics/meetups/issues/90

**Comment by luxas** [comment]
And to note; this will switch us over to city-level (also in the UI) only, the country-level will disappear for now, at least until we find a concrete need for it
