### ISSUE TITLE
Landing page (section 1): Cover and map

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/website#28]
Landing page overview: 
![landing-mockup](https://user-images.githubusercontent.com/4429108/67224353-49c91300-f431-11e9-891e-2fad5de41d20.png)

This focus of this issue is to align section 1 displayed in the overview. 

The issue also covers aligning the objects to fill the fullscreen when on a mobile device, and generally try to make the layout look good for all screen sizes.

**Comment by jepp2078** [comment]
Fixed in https://github.com/cloud-native-nordics/website/pull/39
