### ISSUE TITLE
Landing page (section 2): Slack Invitation

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/website#29]
Landing page overview: 
![landing-mockup](https://user-images.githubusercontent.com/4429108/67224353-49c91300-f431-11e9-891e-2fad5de41d20.png)

This issue focuses on section 2, which handles Slack invitation emails. The functionality of the input field and email invitation sending is already implemented and should be working. 

Definition of done for this issue is to align the overall styling with the mock-up or at least close to, and also handle mobile devices, by making the input field and text fill the screen.

**Comment by jepp2078** [comment]
Closed by https://github.com/cloud-native-nordics/website/pull/39
