### ISSUE TITLE
Landing page (section 6): Footer

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/website#33]
Landing page overview: 
![landing-mockup](https://user-images.githubusercontent.com/4429108/67224353-49c91300-f431-11e9-891e-2fad5de41d20.png)

This focuses on the last section, 6. This sections should be a footer displaying relevant contact information such as our twitter handle, link to github, and to the right a logo for our infrastructure sponsor. 

The definition of done for this includes making it adaptable to mobile devices.

**Comment by kaspernissen** [comment]
This footer should be a component, that can be used on all pages.

**Comment by kaspernissen** [comment]
There's already work done by @Steiniche in this PR https://github.com/cloud-native-nordics/cloud-native-nordics-website/pull/24. We should be able to merge this with master?

**Comment by Steiniche** [comment]
I will merge it with master and do some changes so it reflects the mockup.

**Comment by Steiniche** [comment]
There is still a problem with mobiles.
@jepp2078 do you have an idea of how to solve this?

**Comment by Steiniche** [comment]
Cool!
Just be aware that the current code actually works when using a browser to emulate a mobile screen but not when it is on an actual mobile device.
