### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/website#34]
As we will be removing the "Members" page, this should be replaced with a page displaying all upcoming events.

**Comment by kaspernissen** [comment]
Data has been added. We need styling and we need to get the cover image from meetup com. /cc @jepp2078 @luxas

**Comment by luxas** [comment]
This is done?

**Comment by kaspernissen** [comment]
It's done for now. Let's create new issues that are more specific.
