### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/website#35]
We are currently displaying a search icon in the navigation bar which does not work. 

Wouldn't it be easier to create a seach component, and add it to each the pages; groups, speakers, sponsors, events. This should limit the scope of the functionality and hopefully make it easier instead of general search functionality that searches the entire data model.

**Comment by kaspernissen** [comment]
@jepp2078 you might have some insights on this one.

**Comment by jepp2078** [comment]
Way easier! I think this is the way to go for a start.

**Comment by Steiniche** [comment]
As of https://github.com/cloud-native-nordics/website/pull/24 the search icon is no longer displayed.
I will convert this issue into a new feature instead of a bug.

**Comment by Steiniche** [comment]
@kaspernissen I think this can be moved out of the Go Live?
