### ISSUE TITLE
Rename repo to simply "website"

### ISSUE THREAD

**Issue by luxas** [cloud-native-nordics/website#38]
thoughts @kaspernissen? I think that's neater, and matches expectations from e.g. `kubernetes/website`

**Comment by kaspernissen** [comment]
Yes, that would absolutely make sense 👍

**Comment by Steiniche** [comment]
I have thought of this as well and it will match all our other repos.

**Comment by jepp2078** [comment]
Let's do that!

**Comment by kaspernissen** [comment]
I just renamed 👍
